### PR TITLE
Add relationship

### LINKED ISSUE #5: Add relationship

### PR DESCRIPTION
**Pull request by daria80**
Closes #5

### CODE REVIEW

**Review by camelya58 — COMMENTED** [review]
good job!

**Review by mamadaliev — APPROVED** [review]
Good girl!

**Review by camelya58 — APPROVED** [review]

**Review by darkusss — APPROVED** [review]
Clearest code in the whole world

**Review by daria80 — COMMENTED** [review]
reviewed

**Comment by Vikkingg13** [comment]
Not bad.

**Pull request merged**
