### PR TITLE
Add all services

### LINKED ISSUE #1: Add services
Hi,
please add all services: 
- UserService,
- DayService,
- DayItemService

### PR DESCRIPTION
**Pull request by daria80**
Closes #1

### CODE REVIEW

**Review by daria80 — COMMENTED** [review]
Reviewed

**Review by mamadaliev — COMMENTED** [review]
Reviewed

**Review by Vikkingg13 — COMMENTED** [review]
Good job)

**Review by darkusss — APPROVED** [review]
Well done!

**Pull request merged**
